-- Add summary column to meal_details for short display text
ALTER TABLE meal_details
ADD COLUMN IF NOT EXISTS summary VARCHAR(24);

COMMENT ON COLUMN meal_details.summary IS 'Short summary for display (max 24 characters), generated by LLM';
